heat_template_version: 2015-04-30

description: >
  Deploy Kolla.

parameters:
  NodeCount:
    type: number
    default: 3
    constraints:
      - range: {min: 1}

resources:

  Node:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: NodeCount}
      resource_def:
        type: OS::TripleO::Node
