heat_template_version: 2015-04-30

description: >
  Deploy Kolla.

parameters:
  NodeCount:
    type: number
    default: 2
    constraints:
      - range: {min: 1}

resources:

  Node:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: NodeCount}
      resource_def:
        type: OS::TripleO::Node
  NodeIpListMap:
    type: OS::TripleO::Network::NetIpListMap
    properties:
      ControlPlaneIpList: {get_attr: [Node, ip_address]}

outputs:
  ip_address:
    description: IP address of the server in the ctlplane network
    value: {get_attr: [NodeIpListMap, net_ip_map, ctl_plane]}
