heat_template_version: 2015-04-30

description: >
  Deploy Kolla.

parameters:
  NodeCount:
    type: number
    default: 2
    constraints:
      - range: {min: 1}
  HostnameFormat:
    type: string
    description: Format for Compute node hostnames
    default: '%stackname%-%index%'

resources:
  Node:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: NodeCount}
      resource_def:
        type: OS::TripleO::Node
        properties:
          Hostname:
            str_replace:
              template: {get_param: HostnameFormat}
              params:
                '%stackname%': {get_param: 'OS::stack_name'}

outputs:
  ip_addresses:
    description: IP address of the server in the ctlplane network
    value: {get_attr: [Node, ip_address]}
