heat_template_version: 2014-10-16

parameters:
  DockerRegistry:
    type: string
    default: 127.0.0.1:4000

resources:

  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: start_docker}

  start_docker:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          params:
            $docker_registry: {get_param: DockerRegistry}
          template: {get_file: ./start_docker.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
